child_meal= float(input("What is the price of a child's meal?"))
print(f"Price of child's meal: {child_meal}")
adult_meal= float(input("What is the price of an adult's meal?"))
print(f"Price of an adult's meal: {adult_meal}")
children= int(input("How many children are there?"))
print(f"There are {children} children.")
adults= int(input("How many adults are there?"))
print(f"There are {adults} adult's.")
drinks= float(input("How much do drinks cost?"))
drinks2= int(input("How many do you want?"))
print(f"Okay so {drinks2} drinks.")
sales_tax= float(input("What is the sales tax rate?"))
print(f"The sales tax is: {sales_tax}")
subtotal= float((children * child_meal + adults * adult_meal + drinks2 * drinks))
print(f"Subtotal: ${subtotal:.2f}")
subtax= float((subtotal) * (sales_tax))
subtax2= (subtax)/100
print(f"Sales tax: ${subtax2:.2f}")
total= float(subtotal + subtax2)
print(f"Total: ${total:.2f}")
payment= float(input("What is the payment?"))
change= float((payment - total))
print(f"Change: ${change:.2f}")
print("Thank you for eating with us =)")