print("Please enter the following for your story:")
print("   ")
adjective= input ("Adjective?")
animal= input("Animal?")
verb= input("Verb?")
exclamation= input("Exclamation?")
other_verb= input ("Verb?")
another_verb= input ("Verb?")
print("   ")
print("Your story is:")
print(f"The other day, I was really in trouble. It all started when I saw a very {adjective} {animal} {other_verb} down the hallway.'{exclamation.upper()}!' I yelled. But all I could think to do was to {other_verb} over and over. Miraculously, that caused it to stop, but not before it tried to {another_verb} right in front of my family.")
print("  ")
print("Did you like your story? Try again if you want another story or share with a friend! Thanky you and goodbye.")